'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Public Interface ISmartDeviceApi
    
    Function GetMoldBaseInfoByNR(ByVal moldNR As String) As MoldBaseInfo
    
    Function GetMoldDynamicInfoByMoldNR(ByVal moldNR As String) As MoldDynamicInfo
    
    Function MoldMoveWorkStation(ByVal moldNR As String, ByVal operatorNR As String, ByVal targetWStationNR As String) As Message
End Interface

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(MoldDynamicInfo)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")>  _
Partial Public Class MoldBaseInfo
    
    Private attachField() As Attachment
    
    Private currentPositionField As String
    
    Private fitConnectorField As String
    
    Private fitKnifeField As String
    
    Private materialField As String
    
    Private moldNRField As String
    
    Private nameField As String
    
    Private positionField As String
    
    Private producerField As String
    
    Private projectIdField As String
    
    Private projectNameField As String
    
    Private stateField As MoldStateType
    
    Private stateFieldSpecified As Boolean
    
    Private stateCNField As String
    
    Private typeField As String
    
    Private weightField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=0),  _
     System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")>  _
    Public Property Attach() As Attachment()
        Get
            Return Me.attachField
        End Get
        Set
            Me.attachField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
    Public Property CurrentPosition() As String
        Get
            Return Me.currentPositionField
        End Get
        Set
            Me.currentPositionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
    Public Property FitConnector() As String
        Get
            Return Me.fitConnectorField
        End Get
        Set
            Me.fitConnectorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
    Public Property FitKnife() As String
        Get
            Return Me.fitKnifeField
        End Get
        Set
            Me.fitKnifeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
    Public Property Material() As String
        Get
            Return Me.materialField
        End Get
        Set
            Me.materialField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
    Public Property MoldNR() As String
        Get
            Return Me.moldNRField
        End Get
        Set
            Me.moldNRField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
    Public Property Position() As String
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=8)>  _
    Public Property Producer() As String
        Get
            Return Me.producerField
        End Get
        Set
            Me.producerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=9)>  _
    Public Property ProjectId() As String
        Get
            Return Me.projectIdField
        End Get
        Set
            Me.projectIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=10)>  _
    Public Property ProjectName() As String
        Get
            Return Me.projectNameField
        End Get
        Set
            Me.projectNameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
    Public Property State() As MoldStateType
        Get
            Return Me.stateField
        End Get
        Set
            Me.stateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property StateSpecified() As Boolean
        Get
            Return Me.stateFieldSpecified
        End Get
        Set
            Me.stateFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=12)>  _
    Public Property StateCN() As String
        Get
            Return Me.stateCNField
        End Get
        Set
            Me.stateCNField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=13)>  _
    Public Property Type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=14)>  _
    Public Property Weight() As String
        Get
            Return Me.weightField
        End Get
        Set
            Me.weightField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")>  _
Partial Public Class Attachment
    
    Private attachmentIdField As Integer
    
    Private attachmentIdFieldSpecified As Boolean
    
    Private masterNRField As String
    
    Private typeField As AttachmentType
    
    Private typeFieldSpecified As Boolean
    
    Private dateField As Date
    
    Private dateFieldSpecified As Boolean
    
    Private pathField As String
    
    Private nameField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property AttachmentId() As Integer
        Get
            Return Me.attachmentIdField
        End Get
        Set
            Me.attachmentIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property AttachmentIdSpecified() As Boolean
        Get
            Return Me.attachmentIdFieldSpecified
        End Get
        Set
            Me.attachmentIdFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
    Public Property MasterNR() As String
        Get
            Return Me.masterNRField
        End Get
        Set
            Me.masterNRField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
    Public Property Type() As AttachmentType
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TypeSpecified() As Boolean
        Get
            Return Me.typeFieldSpecified
        End Get
        Set
            Me.typeFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
    Public Property [Date]() As Date
        Get
            Return Me.dateField
        End Get
        Set
            Me.dateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property DateSpecified() As Boolean
        Get
            Return Me.dateFieldSpecified
        End Get
        Set
            Me.dateFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
    Public Property Path() As String
        Get
            Return Me.pathField
        End Get
        Set
            Me.pathField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.ENUM")>  _
Public Enum AttachmentType
    
    '''<remarks/>
    PICTURE
    
    '''<remarks/>
    DOCUMENT
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")>  _
Partial Public Class Message
    
    Private contentField As String
    
    Private msgTypeField As MsgType
    
    Private msgTypeFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
    Public Property Content() As String
        Get
            Return Me.contentField
        End Get
        Set
            Me.contentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
    Public Property MsgType() As MsgType
        Get
            Return Me.msgTypeField
        End Get
        Set
            Me.msgTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property MsgTypeSpecified() As Boolean
        Get
            Return Me.msgTypeFieldSpecified
        End Get
        Set
            Me.msgTypeFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")>  _
Public Enum MsgType
    
    '''<remarks/>
    OK
    
    '''<remarks/>
    Warn
    
    '''<remarks/>
    [Error]
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.ENUM")>  _
Public Enum MoldStateType
    
    '''<remarks/>
    NULL
    
    '''<remarks/>
    NotReturned
    
    '''<remarks/>
    Normal
    
    '''<remarks/>
    NeedMantain
    
    '''<remarks/>
    Broken
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")>  _
Partial Public Class MoldDynamicInfo
    Inherits MoldBaseInfo
    
    Private allowedCuttedTimeField As System.Nullable(Of Integer)
    
    Private allowedCuttedTimeFieldSpecified As Boolean
    
    Private currentCuttedTimeField As System.Nullable(Of Integer)
    
    Private currentCuttedTimeFieldSpecified As Boolean
    
    Private lastMantainTimeField As String
    
    Private lastReleasedTimeField As String
    
    Private mantainCycleField As System.Nullable(Of Integer)
    
    Private mantainCycleFieldSpecified As Boolean
    
    Private operateTimeField As String
    
    Private operatorField As String
    
    Private releaseCycleField As System.Nullable(Of Integer)
    
    Private releaseCycleFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
    Public Property AllowedCuttedTime() As System.Nullable(Of Integer)
        Get
            Return Me.allowedCuttedTimeField
        End Get
        Set
            Me.allowedCuttedTimeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property AllowedCuttedTimeSpecified() As Boolean
        Get
            Return Me.allowedCuttedTimeFieldSpecified
        End Get
        Set
            Me.allowedCuttedTimeFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
    Public Property CurrentCuttedTime() As System.Nullable(Of Integer)
        Get
            Return Me.currentCuttedTimeField
        End Get
        Set
            Me.currentCuttedTimeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property CurrentCuttedTimeSpecified() As Boolean
        Get
            Return Me.currentCuttedTimeFieldSpecified
        End Get
        Set
            Me.currentCuttedTimeFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
    Public Property LastMantainTime() As String
        Get
            Return Me.lastMantainTimeField
        End Get
        Set
            Me.lastMantainTimeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
    Public Property LastReleasedTime() As String
        Get
            Return Me.lastReleasedTimeField
        End Get
        Set
            Me.lastReleasedTimeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
    Public Property MantainCycle() As System.Nullable(Of Integer)
        Get
            Return Me.mantainCycleField
        End Get
        Set
            Me.mantainCycleField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property MantainCycleSpecified() As Boolean
        Get
            Return Me.mantainCycleFieldSpecified
        End Get
        Set
            Me.mantainCycleFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
    Public Property OperateTime() As String
        Get
            Return Me.operateTimeField
        End Get
        Set
            Me.operateTimeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
    Public Property [Operator]() As String
        Get
            Return Me.operatorField
        End Get
        Set
            Me.operatorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
    Public Property ReleaseCycle() As System.Nullable(Of Integer)
        Get
            Return Me.releaseCycleField
        End Get
        Set
            Me.releaseCycleField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ReleaseCycleSpecified() As Boolean
        Get
            Return Me.releaseCycleFieldSpecified
        End Get
        Set
            Me.releaseCycleFieldSpecified = value
        End Set
    End Property
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Xml.Serialization.XmlRootAttribute(ElementName:="GetMoldBaseInfoByNR", [Namespace]:="http://tempuri.org/")>  _
Partial Public Class GetMoldBaseInfoByNRRequest
    
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, [Namespace]:="http://tempuri.org/", Order:=0)>  _
    Public moldNR As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal moldNR As String)
        MyBase.New
        Me.moldNR = moldNR
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Xml.Serialization.XmlRootAttribute(ElementName:="GetMoldBaseInfoByNRResponse", [Namespace]:="http://tempuri.org/")>  _
Partial Public Class GetMoldBaseInfoByNRResponse
    
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, [Namespace]:="http://tempuri.org/", Order:=0)>  _
    Public GetMoldBaseInfoByNRResult As MoldBaseInfo
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetMoldBaseInfoByNRResult As MoldBaseInfo)
        MyBase.New
        Me.GetMoldBaseInfoByNRResult = GetMoldBaseInfoByNRResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Xml.Serialization.XmlRootAttribute(ElementName:="GetMoldDynamicInfoByMoldNR", [Namespace]:="http://tempuri.org/")>  _
Partial Public Class GetMoldDynamicInfoByMoldNRRequest
    
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, [Namespace]:="http://tempuri.org/", Order:=0)>  _
    Public moldNR As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal moldNR As String)
        MyBase.New
        Me.moldNR = moldNR
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Xml.Serialization.XmlRootAttribute(ElementName:="GetMoldDynamicInfoByMoldNRResponse", [Namespace]:="http://tempuri.org/")>  _
Partial Public Class GetMoldDynamicInfoByMoldNRResponse
    
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, [Namespace]:="http://tempuri.org/", Order:=0)>  _
    Public GetMoldDynamicInfoByMoldNRResult As MoldDynamicInfo
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetMoldDynamicInfoByMoldNRResult As MoldDynamicInfo)
        MyBase.New
        Me.GetMoldDynamicInfoByMoldNRResult = GetMoldDynamicInfoByMoldNRResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Xml.Serialization.XmlRootAttribute(ElementName:="MoldMoveWorkStation", [Namespace]:="http://tempuri.org/")>  _
Partial Public Class MoldMoveWorkStationRequest
    
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, [Namespace]:="http://tempuri.org/", Order:=0)>  _
    Public moldNR As String
    
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, [Namespace]:="http://tempuri.org/", Order:=1)>  _
    Public operatorNR As String
    
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, [Namespace]:="http://tempuri.org/", Order:=2)>  _
    Public targetWStationNR As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal moldNR As String, ByVal operatorNR As String, ByVal targetWStationNR As String)
        MyBase.New
        Me.moldNR = moldNR
        Me.operatorNR = operatorNR
        Me.targetWStationNR = targetWStationNR
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Xml.Serialization.XmlRootAttribute(ElementName:="MoldMoveWorkStationResponse", [Namespace]:="http://tempuri.org/")>  _
Partial Public Class MoldMoveWorkStationResponse
    
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, [Namespace]:="http://tempuri.org/", Order:=0)>  _
    Public MoldMoveWorkStationResult As Message
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal MoldMoveWorkStationResult As Message)
        MyBase.New
        Me.MoldMoveWorkStationResult = MoldMoveWorkStationResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Partial Public Class SmartDeviceApiClient
    Inherits Microsoft.Tools.ServiceModel.CFClientBase(Of ISmartDeviceApi)
    Implements ISmartDeviceApi
    
    Public Shared EndpointAddress As System.ServiceModel.EndpointAddress = New System.ServiceModel.EndpointAddress("http://localhost:9090/ToolingWCF/SmartDeviceApi/basic")
    
    Public Sub New()
        Me.New(CreateDefaultBinding, EndpointAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
        addProtectionRequirements(binding)
    End Sub
    
    Private Overloads Function GetMoldBaseInfoByNR(ByVal request As GetMoldBaseInfoByNRRequest) As GetMoldBaseInfoByNRResponse
        Dim info As CFInvokeInfo = New CFInvokeInfo
        info.Action = "http://tempuri.org/ISmartDeviceApi/GetMoldBaseInfoByNR"
        info.RequestIsWrapped = true
        info.ReplyAction = "http://tempuri.org/ISmartDeviceApi/GetMoldBaseInfoByNRResponse"
        info.ResponseIsWrapped = true
        Dim retVal As GetMoldBaseInfoByNRResponse = MyBase.Invoke(Of GetMoldBaseInfoByNRRequest, GetMoldBaseInfoByNRResponse)(info, request)
        Return retVal
    End Function
    
    Public Overloads Function GetMoldBaseInfoByNR(ByVal moldNR As String) As MoldBaseInfo Implements ISmartDeviceApi.GetMoldBaseInfoByNR
        Dim request As GetMoldBaseInfoByNRRequest = New GetMoldBaseInfoByNRRequest(moldNR)
        Dim response As GetMoldBaseInfoByNRResponse = Me.GetMoldBaseInfoByNR(request)
        Return response.GetMoldBaseInfoByNRResult
    End Function
    
    Private Overloads Function GetMoldDynamicInfoByMoldNR(ByVal request As GetMoldDynamicInfoByMoldNRRequest) As GetMoldDynamicInfoByMoldNRResponse
        Dim info As CFInvokeInfo = New CFInvokeInfo
        info.Action = "http://tempuri.org/ISmartDeviceApi/GetMoldDynamicInfoByMoldNR"
        info.RequestIsWrapped = true
        info.ReplyAction = "http://tempuri.org/ISmartDeviceApi/GetMoldDynamicInfoByMoldNRResponse"
        info.ResponseIsWrapped = true
        Dim retVal As GetMoldDynamicInfoByMoldNRResponse = MyBase.Invoke(Of GetMoldDynamicInfoByMoldNRRequest, GetMoldDynamicInfoByMoldNRResponse)(info, request)
        Return retVal
    End Function
    
    Public Overloads Function GetMoldDynamicInfoByMoldNR(ByVal moldNR As String) As MoldDynamicInfo Implements ISmartDeviceApi.GetMoldDynamicInfoByMoldNR
        Dim request As GetMoldDynamicInfoByMoldNRRequest = New GetMoldDynamicInfoByMoldNRRequest(moldNR)
        Dim response As GetMoldDynamicInfoByMoldNRResponse = Me.GetMoldDynamicInfoByMoldNR(request)
        Return response.GetMoldDynamicInfoByMoldNRResult
    End Function
    
    Private Overloads Function MoldMoveWorkStation(ByVal request As MoldMoveWorkStationRequest) As MoldMoveWorkStationResponse
        Dim info As CFInvokeInfo = New CFInvokeInfo
        info.Action = "http://tempuri.org/ISmartDeviceApi/MoldMoveWorkStation"
        info.RequestIsWrapped = true
        info.ReplyAction = "http://tempuri.org/ISmartDeviceApi/MoldMoveWorkStationResponse"
        info.ResponseIsWrapped = true
        Dim retVal As MoldMoveWorkStationResponse = MyBase.Invoke(Of MoldMoveWorkStationRequest, MoldMoveWorkStationResponse)(info, request)
        Return retVal
    End Function
    
    Public Overloads Function MoldMoveWorkStation(ByVal moldNR As String, ByVal operatorNR As String, ByVal targetWStationNR As String) As Message Implements ISmartDeviceApi.MoldMoveWorkStation
        Dim request As MoldMoveWorkStationRequest = New MoldMoveWorkStationRequest(moldNR, operatorNR, targetWStationNR)
        Dim response As MoldMoveWorkStationResponse = Me.MoldMoveWorkStation(request)
        Return response.MoldMoveWorkStationResult
    End Function
    
    Public Shared Function CreateDefaultBinding() As System.ServiceModel.Channels.Binding
        Dim binding As System.ServiceModel.Channels.CustomBinding = New System.ServiceModel.Channels.CustomBinding
        binding.Elements.Add(New System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8))
        binding.Elements.Add(New System.ServiceModel.Channels.HttpTransportBindingElement)
        Return binding
    End Function
    
    Private Sub addProtectionRequirements(ByVal binding As System.ServiceModel.Channels.Binding)
        If (IsSecureMessageBinding(binding) = false) Then
            Return
        End If
        Dim cpr As System.ServiceModel.Security.ChannelProtectionRequirements = New System.ServiceModel.Security.ChannelProtectionRequirements
        ApplyProtection("http://tempuri.org/ISmartDeviceApi/GetMoldBaseInfoByNR", cpr.IncomingSignatureParts, true)
        ApplyProtection("http://tempuri.org/ISmartDeviceApi/GetMoldBaseInfoByNR", cpr.IncomingEncryptionParts, true)
        ApplyProtection("http://tempuri.org/ISmartDeviceApi/GetMoldDynamicInfoByMoldNR", cpr.IncomingSignatureParts, true)
        ApplyProtection("http://tempuri.org/ISmartDeviceApi/GetMoldDynamicInfoByMoldNR", cpr.IncomingEncryptionParts, true)
        ApplyProtection("http://tempuri.org/ISmartDeviceApi/MoldMoveWorkStation", cpr.IncomingSignatureParts, true)
        ApplyProtection("http://tempuri.org/ISmartDeviceApi/MoldMoveWorkStation", cpr.IncomingEncryptionParts, true)
        If (binding.MessageVersion.Addressing Is System.ServiceModel.Channels.AddressingVersion.None) Then
            ApplyProtection("*", cpr.OutgoingSignatureParts, true)
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true)
        Else
            ApplyProtection("http://tempuri.org/ISmartDeviceApi/GetMoldBaseInfoByNRResponse", cpr.OutgoingSignatureParts, true)
            ApplyProtection("http://tempuri.org/ISmartDeviceApi/GetMoldBaseInfoByNRResponse", cpr.OutgoingEncryptionParts, true)
            ApplyProtection("http://tempuri.org/ISmartDeviceApi/GetMoldDynamicInfoByMoldNRResponse", cpr.OutgoingSignatureParts, true)
            ApplyProtection("http://tempuri.org/ISmartDeviceApi/GetMoldDynamicInfoByMoldNRResponse", cpr.OutgoingEncryptionParts, true)
            ApplyProtection("http://tempuri.org/ISmartDeviceApi/MoldMoveWorkStationResponse", cpr.OutgoingSignatureParts, true)
            ApplyProtection("http://tempuri.org/ISmartDeviceApi/MoldMoveWorkStationResponse", cpr.OutgoingEncryptionParts, true)
        End If
        Me.Parameters.Add(cpr)
    End Sub
End Class
