'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3053 版自动生成。
'
Namespace MoldPartInfoSvc
    
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    'CODEGEN: 未处理命名空间“http://www.w3.org/2005/08/addressing”中的可选 WSDL 扩展元素“EndpointReference”。
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="moldpartinfoservice", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MoldPartInfoService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12
            Me.Url = "http://localhost:9090/ToolingWCF/MoldPartInfoService/"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldByMutiConditions", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldByMutiConditions(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal conditions As MoldSearchCondition) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")> MoldBaseInfo()
            Dim results() As Object = Me.Invoke("GetMoldByMutiConditions", New Object() {conditions})
            Return CType(results(0),MoldBaseInfo())
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldByMutiConditions(ByVal conditions As MoldSearchCondition, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldByMutiConditions", New Object() {conditions}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldByMutiConditions(ByVal asyncResult As System.IAsyncResult) As MoldBaseInfo()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),MoldBaseInfo())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldBaseInfoByNR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldBaseInfoByNR(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal moldNR As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> MoldBaseInfo
            Dim results() As Object = Me.Invoke("GetMoldBaseInfoByNR", New Object() {moldNR})
            Return CType(results(0),MoldBaseInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldBaseInfoByNR(ByVal moldNR As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldBaseInfoByNR", New Object() {moldNR}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldBaseInfoByNR(ByVal asyncResult As System.IAsyncResult) As MoldBaseInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),MoldBaseInfo)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldDynamicInfoByMoldNR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldDynamicInfoByMoldNR(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal moldNR As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> MoldDynamicInfo
            Dim results() As Object = Me.Invoke("GetMoldDynamicInfoByMoldNR", New Object() {moldNR})
            Return CType(results(0),MoldDynamicInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldDynamicInfoByMoldNR(ByVal moldNR As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldDynamicInfoByMoldNR", New Object() {moldNR}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldDynamicInfoByMoldNR(ByVal asyncResult As System.IAsyncResult) As MoldDynamicInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),MoldDynamicInfo)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldApplyRecords", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldApplyRecords(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal moldNR As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal applicantId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal startDate As System.Nullable(Of Date), <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal startDateSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal endDate As System.Nullable(Of Date), <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal endDateSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")> StorageRecord()
            Dim results() As Object = Me.Invoke("GetMoldApplyRecords", New Object() {moldNR, applicantId, startDate, startDateSpecified, endDate, endDateSpecified})
            Return CType(results(0),StorageRecord())
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldApplyRecords(ByVal moldNR As String, ByVal applicantId As String, ByVal startDate As System.Nullable(Of Date), ByVal startDateSpecified As Boolean, ByVal endDate As System.Nullable(Of Date), ByVal endDateSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldApplyRecords", New Object() {moldNR, applicantId, startDate, startDateSpecified, endDate, endDateSpecified}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldApplyRecords(ByVal asyncResult As System.IAsyncResult) As StorageRecord()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),StorageRecord())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldApplyRecordsInPages", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldApplyRecordsInPages(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal moldNR As String, ByVal pageIndex As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal pageIndexSpecified As Boolean, ByVal pageSize As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal pageSizeSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal applicantId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal startDate As System.Nullable(Of Date), <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal startDateSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal endDate As System.Nullable(Of Date), <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal endDateSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")> StorageRecord()
            Dim results() As Object = Me.Invoke("GetMoldApplyRecordsInPages", New Object() {moldNR, pageIndex, pageIndexSpecified, pageSize, pageSizeSpecified, applicantId, startDate, startDateSpecified, endDate, endDateSpecified})
            Return CType(results(0),StorageRecord())
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldApplyRecordsInPages(ByVal moldNR As String, ByVal pageIndex As Integer, ByVal pageIndexSpecified As Boolean, ByVal pageSize As Integer, ByVal pageSizeSpecified As Boolean, ByVal applicantId As String, ByVal startDate As System.Nullable(Of Date), ByVal startDateSpecified As Boolean, ByVal endDate As System.Nullable(Of Date), ByVal endDateSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldApplyRecordsInPages", New Object() {moldNR, pageIndex, pageIndexSpecified, pageSize, pageSizeSpecified, applicantId, startDate, startDateSpecified, endDate, endDateSpecified}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldApplyRecordsInPages(ByVal asyncResult As System.IAsyncResult) As StorageRecord()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),StorageRecord())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldReleaseInfoByMoldNR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldReleaseInfoByMoldNR(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal moldNR As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal operatorId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal startDate As System.Nullable(Of Date), <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal startDateSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal endDate As System.Nullable(Of Date), <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal endDateSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")> MoldReleaseInfo()
            Dim results() As Object = Me.Invoke("GetMoldReleaseInfoByMoldNR", New Object() {moldNR, operatorId, startDate, startDateSpecified, endDate, endDateSpecified})
            Return CType(results(0),MoldReleaseInfo())
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldReleaseInfoByMoldNR(ByVal moldNR As String, ByVal operatorId As String, ByVal startDate As System.Nullable(Of Date), ByVal startDateSpecified As Boolean, ByVal endDate As System.Nullable(Of Date), ByVal endDateSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldReleaseInfoByMoldNR", New Object() {moldNR, operatorId, startDate, startDateSpecified, endDate, endDateSpecified}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldReleaseInfoByMoldNR(ByVal asyncResult As System.IAsyncResult) As MoldReleaseInfo()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),MoldReleaseInfo())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldReleaseInfoByMoldNRInPage", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldReleaseInfoByMoldNRInPage(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal moldNR As String, ByVal pageIndex As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal pageIndexSpecified As Boolean, ByVal pageSize As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal pageSizeSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal operatorId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal startDate As System.Nullable(Of Date), <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal startDateSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal endDate As System.Nullable(Of Date), <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal endDateSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")> MoldReleaseInfo()
            Dim results() As Object = Me.Invoke("GetMoldReleaseInfoByMoldNRInPage", New Object() {moldNR, pageIndex, pageIndexSpecified, pageSize, pageSizeSpecified, operatorId, startDate, startDateSpecified, endDate, endDateSpecified})
            Return CType(results(0),MoldReleaseInfo())
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldReleaseInfoByMoldNRInPage(ByVal moldNR As String, ByVal pageIndex As Integer, ByVal pageIndexSpecified As Boolean, ByVal pageSize As Integer, ByVal pageSizeSpecified As Boolean, ByVal operatorId As String, ByVal startDate As System.Nullable(Of Date), ByVal startDateSpecified As Boolean, ByVal endDate As System.Nullable(Of Date), ByVal endDateSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldReleaseInfoByMoldNRInPage", New Object() {moldNR, pageIndex, pageIndexSpecified, pageSize, pageSizeSpecified, operatorId, startDate, startDateSpecified, endDate, endDateSpecified}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldReleaseInfoByMoldNRInPage(ByVal asyncResult As System.IAsyncResult) As MoldReleaseInfo()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),MoldReleaseInfo())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetFileByName", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFileByName(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal fileName As String) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)> Byte()
            Dim results() As Object = Me.Invoke("GetFileByName", New Object() {fileName})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Function BeginGetFileByName(ByVal fileName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFileByName", New Object() {fileName}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetFileByName(ByVal asyncResult As System.IAsyncResult) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldWarnInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldWarnInfo(ByVal type As MoldWarnType, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal typeSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")> MoldWarnInfo()
            Dim results() As Object = Me.Invoke("GetMoldWarnInfo", New Object() {type, typeSpecified})
            Return CType(results(0),MoldWarnInfo())
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldWarnInfo(ByVal type As MoldWarnType, ByVal typeSpecified As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldWarnInfo", New Object() {type, typeSpecified}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldWarnInfo(ByVal asyncResult As System.IAsyncResult) As MoldWarnInfo()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),MoldWarnInfo())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldPositionByNr", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldPositionByNr(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal moldNR As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> Position
            Dim results() As Object = Me.Invoke("GetMoldPositionByNr", New Object() {moldNR})
            Return CType(results(0),Position)
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldPositionByNr(ByVal moldNR As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldPositionByNr", New Object() {moldNR}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldPositionByNr(ByVal asyncResult As System.IAsyncResult) As Position
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Position)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldNrByPosiNr", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldNrByPosiNr(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal posiNr As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GetMoldNrByPosiNr", New Object() {posiNr})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldNrByPosiNr(ByVal posiNr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldNrByPosiNr", New Object() {posiNr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldNrByPosiNr(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMoldPartInfoService/GetMoldCurrentPosition", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMoldCurrentPosition(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal moldNr As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GetMoldCurrentPosition", New Object() {moldNr})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetMoldCurrentPosition(ByVal moldNr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMoldCurrentPosition", New Object() {moldNr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetMoldCurrentPosition(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")>  _
    Partial Public Class MoldSearchCondition
        
        Private moldNRField As String
        
        Private moldTypeIdField As String
        
        Private projectIdField As String
        
        Private stateField As MoldStateType
        
        Private stateFieldSpecified As Boolean
        
        Private warnField As MoldWarnType
        
        Private warnFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MoldNR() As String
            Get
                Return Me.moldNRField
            End Get
            Set
                Me.moldNRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MoldTypeId() As String
            Get
                Return Me.moldTypeIdField
            End Get
            Set
                Me.moldTypeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ProjectId() As String
            Get
                Return Me.projectIdField
            End Get
            Set
                Me.projectIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property State() As MoldStateType
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StateSpecified() As Boolean
            Get
                Return Me.stateFieldSpecified
            End Get
            Set
                Me.stateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Warn() As MoldWarnType
            Get
                Return Me.warnField
            End Get
            Set
                Me.warnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property WarnSpecified() As Boolean
            Get
                Return Me.warnFieldSpecified
            End Get
            Set
                Me.warnFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.ENUM")>  _
    Public Enum MoldStateType
        
        '''<remarks/>
        NULL
        
        '''<remarks/>
        NotReturned
        
        '''<remarks/>
        Normal
        
        '''<remarks/>
        NeedMantain
        
        '''<remarks/>
        Broken
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.ENUM")>  _
    Public Enum MoldWarnType
        
        '''<remarks/>
        NULL
        
        '''<remarks/>
        OutTime
        
        '''<remarks/>
        InTime
    End Enum
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")>  _
    Partial Public Class UniqStorage
        
        Private uniqStorageIdField As String
        
        Private uniqNRField As String
        
        Private positionIdField As String
        
        Private packageNRField As String
        
        Private quantityField As Integer
        
        Private quantityFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property UniqStorageId() As String
            Get
                Return Me.uniqStorageIdField
            End Get
            Set
                Me.uniqStorageIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UniqNR() As String
            Get
                Return Me.uniqNRField
            End Get
            Set
                Me.uniqNRField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PositionId() As String
            Get
                Return Me.positionIdField
            End Get
            Set
                Me.positionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PackageNR() As String
            Get
                Return Me.packageNRField
            End Get
            Set
                Me.packageNRField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity() As Integer
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QuantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")>  _
    Partial Public Class Position
        
        Private positionIDField As String
        
        Private warehouseNRField As String
        
        Private positionNRField As String
        
        Private capicityField As Integer
        
        Private capicityFieldSpecified As Boolean
        
        Private uniqStorageField() As UniqStorage
        
        '''<remarks/>
        Public Property PositionID() As String
            Get
                Return Me.positionIDField
            End Get
            Set
                Me.positionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property WarehouseNR() As String
            Get
                Return Me.warehouseNRField
            End Get
            Set
                Me.warehouseNRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PositionNR() As String
            Get
                Return Me.positionNRField
            End Get
            Set
                Me.positionNRField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Capicity() As Integer
            Get
                Return Me.capicityField
            End Get
            Set
                Me.capicityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CapicitySpecified() As Boolean
            Get
                Return Me.capicityFieldSpecified
            End Get
            Set
                Me.capicityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property UniqStorage() As UniqStorage()
            Get
                Return Me.uniqStorageField
            End Get
            Set
                Me.uniqStorageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")>  _
    Partial Public Class MoldReleaseInfo
        
        Private attachField() As Attachment
        
        Private dateField As System.Nullable(Of Date)
        
        Private dateFieldSpecified As Boolean
        
        Private reportTypeField As ReportType
        
        Private reportTypeFieldSpecified As Boolean
        
        Private reportTypeCNField As String
        
        Private targetNRField As String
        
        Private testerNRField As String
        
        Private testerNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")>  _
        Public Property Attach() As Attachment()
            Get
                Return Me.attachField
            End Get
            Set
                Me.attachField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [Date]() As System.Nullable(Of Date)
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DateSpecified() As Boolean
            Get
                Return Me.dateFieldSpecified
            End Get
            Set
                Me.dateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReportType() As ReportType
            Get
                Return Me.reportTypeField
            End Get
            Set
                Me.reportTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ReportTypeSpecified() As Boolean
            Get
                Return Me.reportTypeFieldSpecified
            End Get
            Set
                Me.reportTypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ReportTypeCN() As String
            Get
                Return Me.reportTypeCNField
            End Get
            Set
                Me.reportTypeCNField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TargetNR() As String
            Get
                Return Me.targetNRField
            End Get
            Set
                Me.targetNRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TesterNR() As String
            Get
                Return Me.testerNRField
            End Get
            Set
                Me.testerNRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TesterName() As String
            Get
                Return Me.testerNameField
            End Get
            Set
                Me.testerNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")>  _
    Partial Public Class Attachment
        
        Private attachmentIdField As Integer
        
        Private attachmentIdFieldSpecified As Boolean
        
        Private masterNRField As String
        
        Private typeField As AttachmentType
        
        Private typeFieldSpecified As Boolean
        
        Private dateField As Date
        
        Private dateFieldSpecified As Boolean
        
        Private pathField As String
        
        Private nameField As String
        
        '''<remarks/>
        Public Property AttachmentId() As Integer
            Get
                Return Me.attachmentIdField
            End Get
            Set
                Me.attachmentIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AttachmentIdSpecified() As Boolean
            Get
                Return Me.attachmentIdFieldSpecified
            End Get
            Set
                Me.attachmentIdFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MasterNR() As String
            Get
                Return Me.masterNRField
            End Get
            Set
                Me.masterNRField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As AttachmentType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TypeSpecified() As Boolean
            Get
                Return Me.typeFieldSpecified
            End Get
            Set
                Me.typeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DateSpecified() As Boolean
            Get
                Return Me.dateFieldSpecified
            End Get
            Set
                Me.dateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Path() As String
            Get
                Return Me.pathField
            End Get
            Set
                Me.pathField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.ENUM")>  _
    Public Enum AttachmentType
        
        '''<remarks/>
        PICTURE
        
        '''<remarks/>
        DOCUMENT
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.ENUM")>  _
    Public Enum ReportType
        
        '''<remarks/>
        MaintainReport
        
        '''<remarks/>
        TestReport
    End Enum
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")>  _
    Partial Public Class StorageRecord
        
        Private storageRecordIdField As Integer
        
        Private storageRecordIdFieldSpecified As Boolean
        
        Private storageRecordNRField As String
        
        Private positionIdField As String
        
        Private sourceField As String
        
        Private destinationField As String
        
        Private operatorIdField As String
        
        Private applicantIdField As String
        
        Private dateField As System.Nullable(Of Date)
        
        Private dateFieldSpecified As Boolean
        
        Private quantityField As System.Nullable(Of Integer)
        
        Private quantityFieldSpecified As Boolean
        
        Private recordTypeField As StorageRecordType
        
        Private recordTypeFieldSpecified As Boolean
        
        Private targetNRField As String
        
        Private remarkField As String
        
        '''<remarks/>
        Public Property StorageRecordId() As Integer
            Get
                Return Me.storageRecordIdField
            End Get
            Set
                Me.storageRecordIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StorageRecordIdSpecified() As Boolean
            Get
                Return Me.storageRecordIdFieldSpecified
            End Get
            Set
                Me.storageRecordIdFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StorageRecordNR() As String
            Get
                Return Me.storageRecordNRField
            End Get
            Set
                Me.storageRecordNRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PositionId() As String
            Get
                Return Me.positionIdField
            End Get
            Set
                Me.positionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Destination() As String
            Get
                Return Me.destinationField
            End Get
            Set
                Me.destinationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OperatorId() As String
            Get
                Return Me.operatorIdField
            End Get
            Set
                Me.operatorIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ApplicantId() As String
            Get
                Return Me.applicantIdField
            End Get
            Set
                Me.applicantIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [Date]() As System.Nullable(Of Date)
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DateSpecified() As Boolean
            Get
                Return Me.dateFieldSpecified
            End Get
            Set
                Me.dateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Quantity() As System.Nullable(Of Integer)
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QuantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RecordType() As StorageRecordType
            Get
                Return Me.recordTypeField
            End Get
            Set
                Me.recordTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RecordTypeSpecified() As Boolean
            Get
                Return Me.recordTypeFieldSpecified
            End Get
            Set
                Me.recordTypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TargetNR() As String
            Get
                Return Me.targetNRField
            End Get
            Set
                Me.targetNRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Remark() As String
            Get
                Return Me.remarkField
            End Get
            Set
                Me.remarkField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.ENUM")>  _
    Public Enum StorageRecordType
        
        '''<remarks/>
        Produce
        
        '''<remarks/>
        Mantain
        
        '''<remarks/>
        Test
        
        '''<remarks/>
        InStore
        
        '''<remarks/>
        OutStore
        
        '''<remarks/>
        MoveStore
        
        '''<remarks/>
        ScrapStore
        
        '''<remarks/>
        [Return]
        
        '''<remarks/>
        MoveWStation
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(MoldWarnInfo)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(MoldDynamicInfo)),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")>  _
    Partial Public Class MoldBaseInfo
        
        Private attachField() As Attachment
        
        Private currentPositionField As String
        
        Private fitConnectorField As String
        
        Private fitKnifeField As String
        
        Private materialField As String
        
        Private moldNRField As String
        
        Private nameField As String
        
        Private positionField As String
        
        Private producerField As String
        
        Private projectIdField As String
        
        Private projectNameField As String
        
        Private stateField As MoldStateType
        
        Private stateFieldSpecified As Boolean
        
        Private stateCNField As String
        
        Private typeField As String
        
        Private weightField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ClassLibrary.Data")>  _
        Public Property Attach() As Attachment()
            Get
                Return Me.attachField
            End Get
            Set
                Me.attachField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CurrentPosition() As String
            Get
                Return Me.currentPositionField
            End Get
            Set
                Me.currentPositionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FitConnector() As String
            Get
                Return Me.fitConnectorField
            End Get
            Set
                Me.fitConnectorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FitKnife() As String
            Get
                Return Me.fitKnifeField
            End Get
            Set
                Me.fitKnifeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Material() As String
            Get
                Return Me.materialField
            End Get
            Set
                Me.materialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MoldNR() As String
            Get
                Return Me.moldNRField
            End Get
            Set
                Me.moldNRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Position() As String
            Get
                Return Me.positionField
            End Get
            Set
                Me.positionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Producer() As String
            Get
                Return Me.producerField
            End Get
            Set
                Me.producerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ProjectId() As String
            Get
                Return Me.projectIdField
            End Get
            Set
                Me.projectIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ProjectName() As String
            Get
                Return Me.projectNameField
            End Get
            Set
                Me.projectNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property State() As MoldStateType
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StateSpecified() As Boolean
            Get
                Return Me.stateFieldSpecified
            End Get
            Set
                Me.stateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StateCN() As String
            Get
                Return Me.stateCNField
            End Get
            Set
                Me.stateCNField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Weight() As String
            Get
                Return Me.weightField
            End Get
            Set
                Me.weightField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")>  _
    Partial Public Class MoldWarnInfo
        Inherits MoldBaseInfo
        
        Private disMinuteField As Double
        
        Private disMinuteFieldSpecified As Boolean
        
        Private disTimeTextField As String
        
        Private lendTimeField As Date
        
        Private lendTimeFieldSpecified As Boolean
        
        Private maxLendHourField As Double
        
        Private maxLendHourFieldSpecified As Boolean
        
        Private minusField As Boolean
        
        Private minusFieldSpecified As Boolean
        
        Private shouldReTimeField As Date
        
        Private shouldReTimeFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property DisMinute() As Double
            Get
                Return Me.disMinuteField
            End Get
            Set
                Me.disMinuteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DisMinuteSpecified() As Boolean
            Get
                Return Me.disMinuteFieldSpecified
            End Get
            Set
                Me.disMinuteFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DisTimeText() As String
            Get
                Return Me.disTimeTextField
            End Get
            Set
                Me.disTimeTextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LendTime() As Date
            Get
                Return Me.lendTimeField
            End Get
            Set
                Me.lendTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LendTimeSpecified() As Boolean
            Get
                Return Me.lendTimeFieldSpecified
            End Get
            Set
                Me.lendTimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MaxLendHour() As Double
            Get
                Return Me.maxLendHourField
            End Get
            Set
                Me.maxLendHourField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MaxLendHourSpecified() As Boolean
            Get
                Return Me.maxLendHourFieldSpecified
            End Get
            Set
                Me.maxLendHourFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Minus() As Boolean
            Get
                Return Me.minusField
            End Get
            Set
                Me.minusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MinusSpecified() As Boolean
            Get
                Return Me.minusFieldSpecified
            End Get
            Set
                Me.minusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShouldReTime() As Date
            Get
                Return Me.shouldReTimeField
            End Get
            Set
                Me.shouldReTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ShouldReTimeSpecified() As Boolean
            Get
                Return Me.shouldReTimeFieldSpecified
            End Get
            Set
                Me.shouldReTimeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ToolingWCF.DataModel")>  _
    Partial Public Class MoldDynamicInfo
        Inherits MoldBaseInfo
        
        Private allowedCuttedTimeField As System.Nullable(Of Integer)
        
        Private allowedCuttedTimeFieldSpecified As Boolean
        
        Private currentCuttedTimeField As System.Nullable(Of Integer)
        
        Private currentCuttedTimeFieldSpecified As Boolean
        
        Private lastMantainTimeField As String
        
        Private lastReleasedTimeField As String
        
        Private mantainCycleField As System.Nullable(Of Integer)
        
        Private mantainCycleFieldSpecified As Boolean
        
        Private operateTimeField As String
        
        Private operatorField As String
        
        Private releaseCycleField As System.Nullable(Of Integer)
        
        Private releaseCycleFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AllowedCuttedTime() As System.Nullable(Of Integer)
            Get
                Return Me.allowedCuttedTimeField
            End Get
            Set
                Me.allowedCuttedTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AllowedCuttedTimeSpecified() As Boolean
            Get
                Return Me.allowedCuttedTimeFieldSpecified
            End Get
            Set
                Me.allowedCuttedTimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CurrentCuttedTime() As System.Nullable(Of Integer)
            Get
                Return Me.currentCuttedTimeField
            End Get
            Set
                Me.currentCuttedTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CurrentCuttedTimeSpecified() As Boolean
            Get
                Return Me.currentCuttedTimeFieldSpecified
            End Get
            Set
                Me.currentCuttedTimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LastMantainTime() As String
            Get
                Return Me.lastMantainTimeField
            End Get
            Set
                Me.lastMantainTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LastReleasedTime() As String
            Get
                Return Me.lastReleasedTimeField
            End Get
            Set
                Me.lastReleasedTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MantainCycle() As System.Nullable(Of Integer)
            Get
                Return Me.mantainCycleField
            End Get
            Set
                Me.mantainCycleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MantainCycleSpecified() As Boolean
            Get
                Return Me.mantainCycleFieldSpecified
            End Get
            Set
                Me.mantainCycleFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OperateTime() As String
            Get
                Return Me.operateTimeField
            End Get
            Set
                Me.operateTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [Operator]() As String
            Get
                Return Me.operatorField
            End Get
            Set
                Me.operatorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ReleaseCycle() As System.Nullable(Of Integer)
            Get
                Return Me.releaseCycleField
            End Get
            Set
                Me.releaseCycleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ReleaseCycleSpecified() As Boolean
            Get
                Return Me.releaseCycleFieldSpecified
            End Get
            Set
                Me.releaseCycleFieldSpecified = value
            End Set
        End Property
    End Class
End Namespace
